name: php_parser_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  json_serializable: ^6.3.2

dev_dependencies:
  test: ^1.20.1
  very_good_analysis: ^3.0.2
